name: Build new client release and publish to PyPI

on:
  push:
    branches: ["release-client"]
  workflow_dispatch:

jobs:
  build:
    name: Build distribution from release-client branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: "release-client"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install pypa/build
        run: >-
          python3 -m pip install build --user

      - name: Build a binary wheel and a source tarball
        working-directory: ./clients/python
        run: python3 -m build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: aepsych_client_dist
          path: ./clients/python/dist/

  publish-to-testpypi:
    name: Publish dist to TestPyPI
    needs:
      - build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/aepsych-client

    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: aepsych_client_dist
          path: dist/

      - name: Publish dis to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  test-dist:
    name: Test distribtion from TestPyPI
    needs:
      - publish-to-testpypi
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [macos-latest, windows-latest, macos-13]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple "aepsych_client"

      - name: Check if python is importable
        run: |
          python -c "import aepsych_client"

  publish-to-pypi:
    name: Publish dist to PyPI
    needs:
      - test-dist
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/aepsych-client
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: aepsych_client_dist
          path: dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  update-main-version:
    name: Update main version number
    needs:
        - publish-to-pypi
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: "release-client"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install repo and get version
        run: |
          python3 -m pip install .
          echo "version=$(python -c "import aepsych_client; print(aepsych_client.__version__)")" >> "$GITHUB_ENV"

      - uses: actions/checkout@v4
        with:
          ref: "main"

      - name: Edit main version with dev appended
        run: |
          sed -i "s/^__version__ .*/__version__ = \""$version"+dev\"/" clients/python/aepsych_client/version.py

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update main client version to ${{ env.version }}+dev
          title: Automated main client version bump to ${{ env.version }}+dev
          body: Update main client version to ${{ env.version }}+dev due to release.
